import { AuthContextProvider } from "@/context/auth";
import "./globals.css";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={`antialiased text-slate-500 dark:text-slate-400 bg-zinc-50 dark:bg-slate-900 ${inter.className}`}
			>
				<AuthContextProvider cookie={cookies().get("token")}>
					<Header />
					{children}
				</AuthContextProvider>
			</body>
		</html>
	);
}
