import { AuthContextProvider } from "@/context/auth";
import "./globals.css";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<AuthContextProvider cookie={cookies().get("token")}>
					{children}
				</AuthContextProvider>
			</body>
		</html>
	);
}
